[tool.poetry]
name = "awel-flow-rag-chat-example"
version = "0.1.0"
description = ""
authors = ["aries_ckt <916701291@qq.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
