[flow]
label = "AWEL Flow Example Streaming Chat"
# A unique name for all dbgpts
name = "awel_flow_example_chat"
version = "0.1.0"
description = "An example of a streaming chat flow. It uses a simple chat flow to demonstrate how to use the flow to handle user's request and response with streamming format. The flow is defined in a JSON file."
authors = ["Fangyin Cheng <staneyffer@gmail.com>"]
# How to define the flow, python or json
definition_type = "json"

[python_config]

# Json config
[json_config]
file_path = "definition/flow_definition.json"